# Generated by Django 2.0.10 on 2019-05-12 22:13

import constrainedfilefield.fields.file
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_from', models.DateField(default=datetime.date.today)),
                ('date_to', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('web', models.URLField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('access_key', models.CharField(max_length=256, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('preview_small', models.ImageField(blank=True, upload_to='jpeg/')),
                ('preview_large', models.ImageField(blank=True, upload_to='jpeg/')),
                ('pdf', constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['application/pdf'], max_upload_size=10240000, mime_lookup_length=4096, upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='PosterAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posters.Author')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posters.Poster')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='poster',
            name='authors',
            field=models.ManyToManyField(through='posters.PosterAuthor', to='posters.Author'),
        ),
        migrations.AddField(
            model_name='poster',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posters.Conference'),
        ),
    ]
