# Generated by Django 2.0.10 on 2019-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterauthor',
            name='email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posterauthor',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
