# Generated by Django 2.0.10 on 2019-05-13 16:10

import constrainedfilefield.fields.file
from django.db import migrations, models
import unique_upload.unique_upload


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='pdf',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['application/pdf'], max_upload_size=10240000, mime_lookup_length=4096, upload_to=unique_upload.unique_upload.unique_upload),
        ),
        migrations.AlterField(
            model_name='poster',
            name='preview_large',
            field=models.ImageField(blank=True, upload_to=unique_upload.unique_upload.unique_upload),
        ),
        migrations.AlterField(
            model_name='poster',
            name='preview_small',
            field=models.ImageField(blank=True, upload_to=unique_upload.unique_upload.unique_upload),
        ),
    ]
