# Generated by Django 2.0.10 on 2019-05-14 16:00

import constrainedfilefield.fields.file
from django.db import migrations, models
import unique_upload.unique_upload


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_auto_20190513_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
