# Generated by Django 2.0.10 on 2019-06-03 21:46

import constrainedfilefield.fields.file
from django.db import migrations, models
import unique_upload.unique_upload


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_auto_20190514_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slug',
            field=models.SlugField(default='default', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
