# Generated by Django 2.0.10 on 2019-12-03 23:47

import constrainedfilefield.fields.file
from django.db import migrations, models
import unique_upload.unique_upload


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0005_auto_20190709_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='external_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
